---
title: "analysis"
author: "you"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE
)
library(ampvis2)
library(tidyverse) 
```

# Load some data
```{r}
asvtable <- amp_import_usearch(otutab = "C:/Users/Lab PC/OneDrive - Aalborg Universitet/Aalborg/5. Research AAU/210601_Modelling/Damhusaaen/ASVtable_notax.tsv",  
                               sintax = "C:/Users/Lab PC/OneDrive - Aalborg Universitet/Aalborg/5. Research AAU/210601_Modelling/Damhusaaen/ASVs.R1.sintax") 
 
metadata <- readxl::read_excel("C:/Users/Lab PC/OneDrive - Aalborg Universitet/Aalborg/5. Research AAU/210601_Modelling/Damhusaaen/metadata_DAM_sequencing.xlsx") 
 
metadata$SampleDate <- as.Date(metadata$SampleDate , format = "%Y-%m-%d") 
metadata$year <- lubridate::year(metadata$SampleDate) 
 
allampvis <- amp_load(otutable = asvtable,  
                      metadata = metadata) 
```

# Do some QC
```{r}
allampvis <- amp_subset_samples(allampvis, minreads = 10000, normalise = FALSE) 
 
allampvis <- amp_subset_samples(allampvis, year == "2019") 
 
rm(asvtable, metadata) 
```

# Alpha-diversity check, octave plots
```{r}
alpha_div <- amp_alphadiv(allampvis, 
             rarefy = 10080) 
 
amp_octave(allampvis, 
           tax_aggregate = "OTU") 
 
ggsave("octave.png", 
       plot = last_plot(), 
       height = 40, 
       width = 40, 
       dpi = 300) 
```

# Make a simple overview heatmap
```{r}
amp_heatmap(allampvis, 
            group_by = "SampleDate", 
            facet_by = "SampleContent", 
            tax_aggregate = "Genus", 
            tax_show = 15, 
            plot_colorscale = "sqrt") 
```

# Fix this code
```{r}
data.frame(class = unlist(lapply(mpg, class)))
```

